site_name: Daisy User Guide
site_description: User documentation for the Daisy agricultural simulation model
site_url: https://daisy-model.github.io/daisy/
repo_url: https://github.com/daisy-model/daisy
repo_name: daisy-model/daisy
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - MacOS: getting-started/macos.md
    - Windows: getting-started/windows.md
  - Editor Setup:
    - Visual Studio Code: editors/vscode.md
    - TextPad: editors/textpad.md
  - Python Setup: python-setup.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
