# Windows package
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_GENERATOR NSIS)
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CMAKE_PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-python${DAISY_PYTHON_VERSION}")
set(DAISY_PACKAGE_FILE_NAME ${CPACK_PACKAGE_FILE_NAME})
