if (${OS} STREQUAL "mingw" OR ${OS} STREQUAL "macos")
  if (NOT DEFINED UV_INSTALLED_PYTHON_ROOT_DIR)
    message(FATAL_ERROR "You must set UV_INSTALLED_PYTHON_ROOT_DIR to ensure building against specific python version")
  endif()
  set(Python_ROOT_DIR ${UV_INSTALLED_PYTHON_ROOT_DIR})
endif()
set(PYBIND11_FINDPYTHON ON)
find_package(pybind11 REQUIRED)
link_libraries(pybind11::embed)
